name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
      - develop
              
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version : 17
          distribution : 'adopt'

     #finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: TP1 Docker/TP1_Docker_Backend/simple-api
        run: mvn clean verify
            
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --malicka --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t my-docker-image:latest .
          docker push my-docker-image:latest
